In [1]:
import numpy as np

---
# Práctico 8 - Cadenas de Markov

# Cálculos matriciales

In [19]:
#Elevar una matriz a un d exponente
import sympy as sp


Q = sp.Matrix([
    [sp.Rational(1,4), sp.Rational(1,2), sp.Rational(1,4)],
    [sp.Rational(1,2), sp.Rational(0)  , sp.Rational(1,2)],
    [sp.Rational(1,2), sp.Rational(1,2), sp.Rational(1,2)]
]
)

sp.pprint(Q @ Q @ Q @ Q)

⎡143  29  143⎤
⎢───  ──  ───⎥
⎢256  64  256⎥
⎢            ⎥
⎢75   17  75 ⎥
⎢───  ──  ───⎥
⎢128  32  128⎥
⎢            ⎥
⎢109  23  109⎥
⎢───  ──  ───⎥
⎣128  32  128⎦


In [20]:

Q = [
    [0.25, 0.5, 0.25],
    [0.5 ,  0 , 0.5 ],
    [0.5 , 0.5, 0.5 ]
]

n = 3

print("Matriz Q")
print("------ -")
for fila in Q:
    print("[" + "  ".join(f"{x:>4.2f}" for x in fila) + "]")


Matriz Q
------ -
[0.25  0.50  0.25]
[0.50  0.00  0.50]
[0.50  0.50  0.50]


In [21]:
EXPON = 4
Q = np.linalg.matrix_power(Q, EXPON)
print(f"Matriz Q^{EXPON}")
print("------ ---")
for fila in Q:
    print("[" + "  ".join(f"{x:>4.2f}" for x in fila) + "]")

Matriz Q^4
------ ---
[0.56  0.45  0.56]
[0.59  0.53  0.59]
[0.85  0.72  0.85]
